# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow8.ui'
#
# Created: Mon May 25 15:29:41 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(QtGui.QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1133, 706)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_8 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 2)
        self.comboBox_FN = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_FN.sizePolicy().hasHeightForWidth())
        self.comboBox_FN.setSizePolicy(sizePolicy)
        self.comboBox_FN.setObjectName(_fromUtf8("comboBox_FN"))
        self.gridLayout_5.addWidget(self.comboBox_FN, 0, 2, 1, 1)
        self.groupBox_FC = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_FC.sizePolicy().hasHeightForWidth())
        self.groupBox_FC.setSizePolicy(sizePolicy)
        self.groupBox_FC.setObjectName(_fromUtf8("groupBox_FC"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_FC)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboBox_FC = QtGui.QComboBox(self.groupBox_FC)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        self.comboBox_FC.setFont(font)
        self.comboBox_FC.setObjectName(_fromUtf8("comboBox_FC"))
        self.comboBox_FC.addItem(_fromUtf8(""))
        self.comboBox_FC.addItem(_fromUtf8(""))
        self.comboBox_FC.addItem(_fromUtf8(""))
        self.comboBox_FC.addItem(_fromUtf8(""))
        self.comboBox_FC.addItem(_fromUtf8(""))
        self.comboBox_FC.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_FC, 0, 0, 1, 2)
        self.label_Xval = QtGui.QLabel(self.groupBox_FC)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Xval.sizePolicy().hasHeightForWidth())
        self.label_Xval.setSizePolicy(sizePolicy)
        self.label_Xval.setObjectName(_fromUtf8("label_Xval"))
        self.gridLayout.addWidget(self.label_Xval, 1, 0, 1, 1)
        self.lineEdit_Xval = QtGui.QLineEdit(self.groupBox_FC)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Xval.sizePolicy().hasHeightForWidth())
        self.lineEdit_Xval.setSizePolicy(sizePolicy)
        self.lineEdit_Xval.setObjectName(_fromUtf8("lineEdit_Xval"))
        self.gridLayout.addWidget(self.lineEdit_Xval, 1, 1, 1, 1)
        self.label_Yval = QtGui.QLabel(self.groupBox_FC)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Yval.sizePolicy().hasHeightForWidth())
        self.label_Yval.setSizePolicy(sizePolicy)
        self.label_Yval.setObjectName(_fromUtf8("label_Yval"))
        self.gridLayout.addWidget(self.label_Yval, 2, 0, 1, 1)
        self.lineEdit_Yval = QtGui.QLineEdit(self.groupBox_FC)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Yval.sizePolicy().hasHeightForWidth())
        self.lineEdit_Yval.setSizePolicy(sizePolicy)
        self.lineEdit_Yval.setObjectName(_fromUtf8("lineEdit_Yval"))
        self.gridLayout.addWidget(self.lineEdit_Yval, 2, 1, 1, 1)
        self.label_FCError = QtGui.QLabel(self.groupBox_FC)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_FCError.sizePolicy().hasHeightForWidth())
        self.label_FCError.setSizePolicy(sizePolicy)
        self.label_FCError.setObjectName(_fromUtf8("label_FCError"))
        self.gridLayout.addWidget(self.label_FCError, 3, 0, 1, 1)
        self.label_FCErrorShow = QtGui.QLabel(self.groupBox_FC)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_FCErrorShow.sizePolicy().hasHeightForWidth())
        self.label_FCErrorShow.setSizePolicy(sizePolicy)
        self.label_FCErrorShow.setToolTip(_fromUtf8(""))
        self.label_FCErrorShow.setObjectName(_fromUtf8("label_FCErrorShow"))
        self.gridLayout.addWidget(self.label_FCErrorShow, 3, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_FC, 1, 0, 1, 3)
        self.checkBox_Bounds = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Bounds.sizePolicy().hasHeightForWidth())
        self.checkBox_Bounds.setSizePolicy(sizePolicy)
        self.checkBox_Bounds.setObjectName(_fromUtf8("checkBox_Bounds"))
        self.gridLayout_5.addWidget(self.checkBox_Bounds, 2, 0, 1, 1)
        self.checkBox_UE = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_UE.sizePolicy().hasHeightForWidth())
        self.checkBox_UE.setSizePolicy(sizePolicy)
        self.checkBox_UE.setObjectName(_fromUtf8("checkBox_UE"))
        self.gridLayout_5.addWidget(self.checkBox_UE, 2, 1, 1, 1)
        self.pushButton_FC = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_FC.sizePolicy().hasHeightForWidth())
        self.pushButton_FC.setSizePolicy(sizePolicy)
        self.pushButton_FC.setObjectName(_fromUtf8("pushButton_FC"))
        self.gridLayout_5.addWidget(self.pushButton_FC, 2, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.graphicsView_FC = PlotWidget(self.centralwidget)
        self.graphicsView_FC.setObjectName(_fromUtf8("graphicsView_FC"))
        self.gridLayout_8.addWidget(self.graphicsView_FC, 0, 1, 1, 1)
        self.treeWidget_FC = QtGui.QTreeWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_FC.sizePolicy().hasHeightForWidth())
        self.treeWidget_FC.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        self.treeWidget_FC.setFont(font)
        self.treeWidget_FC.setObjectName(_fromUtf8("treeWidget_FC"))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget_FC.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget_FC.headerItem().setFont(1, font)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_FC)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_FC)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_FC)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_FC)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_FC)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_FC)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        self.treeWidget_FC.header().setSortIndicatorShown(False)
        self.gridLayout_8.addWidget(self.treeWidget_FC, 0, 2, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_YL = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_YL.sizePolicy().hasHeightForWidth())
        self.label_YL.setSizePolicy(sizePolicy)
        self.label_YL.setObjectName(_fromUtf8("label_YL"))
        self.gridLayout_7.addWidget(self.label_YL, 0, 0, 1, 2)
        self.comboBox_YL = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_YL.sizePolicy().hasHeightForWidth())
        self.comboBox_YL.setSizePolicy(sizePolicy)
        self.comboBox_YL.setObjectName(_fromUtf8("comboBox_YL"))
        self.comboBox_YL.addItem(_fromUtf8(""))
        self.comboBox_YL.addItem(_fromUtf8(""))
        self.comboBox_YL.addItem(_fromUtf8(""))
        self.comboBox_YL.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.comboBox_YL, 0, 2, 1, 1)
        self.tabWidget_Input = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_Input.sizePolicy().hasHeightForWidth())
        self.tabWidget_Input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        self.tabWidget_Input.setFont(font)
        self.tabWidget_Input.setObjectName(_fromUtf8("tabWidget_Input"))
        self.tab_Vonmises = QtGui.QWidget()
        self.tab_Vonmises.setObjectName(_fromUtf8("tab_Vonmises"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_Vonmises)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_Vonmises_ay = QtGui.QLabel(self.tab_Vonmises)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Vonmises_ay.sizePolicy().hasHeightForWidth())
        self.label_Vonmises_ay.setSizePolicy(sizePolicy)
        self.label_Vonmises_ay.setObjectName(_fromUtf8("label_Vonmises_ay"))
        self.gridLayout_4.addWidget(self.label_Vonmises_ay, 0, 0, 1, 1)
        self.lineEdit_Vonmises_ay = QtGui.QLineEdit(self.tab_Vonmises)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Vonmises_ay.sizePolicy().hasHeightForWidth())
        self.lineEdit_Vonmises_ay.setSizePolicy(sizePolicy)
        self.lineEdit_Vonmises_ay.setObjectName(_fromUtf8("lineEdit_Vonmises_ay"))
        self.gridLayout_4.addWidget(self.lineEdit_Vonmises_ay, 0, 1, 1, 1)
        self.tabWidget_Input.addTab(self.tab_Vonmises, _fromUtf8(""))
        self.tab_Hill48 = QtGui.QWidget()
        self.tab_Hill48.setObjectName(_fromUtf8("tab_Hill48"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_Hill48)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_Hill_a0 = QtGui.QLabel(self.tab_Hill48)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Hill_a0.sizePolicy().hasHeightForWidth())
        self.label_Hill_a0.setSizePolicy(sizePolicy)
        self.label_Hill_a0.setObjectName(_fromUtf8("label_Hill_a0"))
        self.gridLayout_3.addWidget(self.label_Hill_a0, 0, 0, 1, 1)
        self.lineEdit_Hill_a0 = QtGui.QLineEdit(self.tab_Hill48)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Hill_a0.sizePolicy().hasHeightForWidth())
        self.lineEdit_Hill_a0.setSizePolicy(sizePolicy)
        self.lineEdit_Hill_a0.setObjectName(_fromUtf8("lineEdit_Hill_a0"))
        self.gridLayout_3.addWidget(self.lineEdit_Hill_a0, 0, 1, 1, 1)
        self.label_Hill_r0 = QtGui.QLabel(self.tab_Hill48)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Hill_r0.sizePolicy().hasHeightForWidth())
        self.label_Hill_r0.setSizePolicy(sizePolicy)
        self.label_Hill_r0.setObjectName(_fromUtf8("label_Hill_r0"))
        self.gridLayout_3.addWidget(self.label_Hill_r0, 1, 0, 1, 1)
        self.lineEdit_Hill_r0 = QtGui.QLineEdit(self.tab_Hill48)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Hill_r0.sizePolicy().hasHeightForWidth())
        self.lineEdit_Hill_r0.setSizePolicy(sizePolicy)
        self.lineEdit_Hill_r0.setObjectName(_fromUtf8("lineEdit_Hill_r0"))
        self.gridLayout_3.addWidget(self.lineEdit_Hill_r0, 1, 1, 1, 1)
        self.label_Hill_r90 = QtGui.QLabel(self.tab_Hill48)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Hill_r90.sizePolicy().hasHeightForWidth())
        self.label_Hill_r90.setSizePolicy(sizePolicy)
        self.label_Hill_r90.setObjectName(_fromUtf8("label_Hill_r90"))
        self.gridLayout_3.addWidget(self.label_Hill_r90, 2, 0, 1, 1)
        self.lineEdit_Hill_r90 = QtGui.QLineEdit(self.tab_Hill48)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Hill_r90.sizePolicy().hasHeightForWidth())
        self.lineEdit_Hill_r90.setSizePolicy(sizePolicy)
        self.lineEdit_Hill_r90.setObjectName(_fromUtf8("lineEdit_Hill_r90"))
        self.gridLayout_3.addWidget(self.lineEdit_Hill_r90, 2, 1, 1, 1)
        self.tabWidget_Input.addTab(self.tab_Hill48, _fromUtf8(""))
        self.tab_Yld2000_2d = QtGui.QWidget()
        self.tab_Yld2000_2d.setObjectName(_fromUtf8("tab_Yld2000_2d"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_Yld2000_2d)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_Yld_a0 = QtGui.QLabel(self.tab_Yld2000_2d)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Yld_a0.sizePolicy().hasHeightForWidth())
        self.label_Yld_a0.setSizePolicy(sizePolicy)
        self.label_Yld_a0.setObjectName(_fromUtf8("label_Yld_a0"))
        self.gridLayout_2.addWidget(self.label_Yld_a0, 0, 0, 1, 1)
        self.lineEdit_Yld_a0 = QtGui.QLineEdit(self.tab_Yld2000_2d)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Yld_a0.sizePolicy().hasHeightForWidth())
        self.lineEdit_Yld_a0.setSizePolicy(sizePolicy)
        self.lineEdit_Yld_a0.setObjectName(_fromUtf8("lineEdit_Yld_a0"))
        self.gridLayout_2.addWidget(self.lineEdit_Yld_a0, 0, 1, 1, 1)
        self.label_Yld_a45 = QtGui.QLabel(self.tab_Yld2000_2d)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Yld_a45.sizePolicy().hasHeightForWidth())
        self.label_Yld_a45.setSizePolicy(sizePolicy)
        self.label_Yld_a45.setObjectName(_fromUtf8("label_Yld_a45"))
        self.gridLayout_2.addWidget(self.label_Yld_a45, 1, 0, 1, 1)
        self.lineEdit_Yld_a45 = QtGui.QLineEdit(self.tab_Yld2000_2d)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Yld_a45.sizePolicy().hasHeightForWidth())
        self.lineEdit_Yld_a45.setSizePolicy(sizePolicy)
        self.lineEdit_Yld_a45.setObjectName(_fromUtf8("lineEdit_Yld_a45"))
        self.gridLayout_2.addWidget(self.lineEdit_Yld_a45, 1, 1, 1, 1)
        self.label_Yld_a90 = QtGui.QLabel(self.tab_Yld2000_2d)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Yld_a90.sizePolicy().hasHeightForWidth())
        self.label_Yld_a90.setSizePolicy(sizePolicy)
        self.label_Yld_a90.setObjectName(_fromUtf8("label_Yld_a90"))
        self.gridLayout_2.addWidget(self.label_Yld_a90, 2, 0, 1, 1)
        self.lineEdit_Yld_a90 = QtGui.QLineEdit(self.tab_Yld2000_2d)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Yld_a90.sizePolicy().hasHeightForWidth())
        self.lineEdit_Yld_a90.setSizePolicy(sizePolicy)
        self.lineEdit_Yld_a90.setObjectName(_fromUtf8("lineEdit_Yld_a90"))
        self.gridLayout_2.addWidget(self.lineEdit_Yld_a90, 2, 1, 1, 1)
        self.label_Yld_ab = QtGui.QLabel(self.tab_Yld2000_2d)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Yld_ab.sizePolicy().hasHeightForWidth())
        self.label_Yld_ab.setSizePolicy(sizePolicy)
        self.label_Yld_ab.setObjectName(_fromUtf8("label_Yld_ab"))
        self.gridLayout_2.addWidget(self.label_Yld_ab, 3, 0, 1, 1)
        self.lineEdit_Yld_ab = QtGui.QLineEdit(self.tab_Yld2000_2d)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Yld_ab.sizePolicy().hasHeightForWidth())
        self.lineEdit_Yld_ab.setSizePolicy(sizePolicy)
        self.lineEdit_Yld_ab.setObjectName(_fromUtf8("lineEdit_Yld_ab"))
        self.gridLayout_2.addWidget(self.lineEdit_Yld_ab, 3, 1, 1, 1)
        self.label_Yld_r0 = QtGui.QLabel(self.tab_Yld2000_2d)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Yld_r0.sizePolicy().hasHeightForWidth())
        self.label_Yld_r0.setSizePolicy(sizePolicy)
        self.label_Yld_r0.setObjectName(_fromUtf8("label_Yld_r0"))
        self.gridLayout_2.addWidget(self.label_Yld_r0, 4, 0, 1, 1)
        self.lineEdit_Yld_r0 = QtGui.QLineEdit(self.tab_Yld2000_2d)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Yld_r0.sizePolicy().hasHeightForWidth())
        self.lineEdit_Yld_r0.setSizePolicy(sizePolicy)
        self.lineEdit_Yld_r0.setObjectName(_fromUtf8("lineEdit_Yld_r0"))
        self.gridLayout_2.addWidget(self.lineEdit_Yld_r0, 4, 1, 1, 1)
        self.label_Yld_r45 = QtGui.QLabel(self.tab_Yld2000_2d)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Yld_r45.sizePolicy().hasHeightForWidth())
        self.label_Yld_r45.setSizePolicy(sizePolicy)
        self.label_Yld_r45.setObjectName(_fromUtf8("label_Yld_r45"))
        self.gridLayout_2.addWidget(self.label_Yld_r45, 5, 0, 1, 1)
        self.lineEdit_Yld_r45 = QtGui.QLineEdit(self.tab_Yld2000_2d)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Yld_r45.sizePolicy().hasHeightForWidth())
        self.lineEdit_Yld_r45.setSizePolicy(sizePolicy)
        self.lineEdit_Yld_r45.setObjectName(_fromUtf8("lineEdit_Yld_r45"))
        self.gridLayout_2.addWidget(self.lineEdit_Yld_r45, 5, 1, 1, 1)
        self.label_Yld_r90 = QtGui.QLabel(self.tab_Yld2000_2d)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Yld_r90.sizePolicy().hasHeightForWidth())
        self.label_Yld_r90.setSizePolicy(sizePolicy)
        self.label_Yld_r90.setObjectName(_fromUtf8("label_Yld_r90"))
        self.gridLayout_2.addWidget(self.label_Yld_r90, 6, 0, 1, 1)
        self.lineEdit_Yld_r90 = QtGui.QLineEdit(self.tab_Yld2000_2d)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Yld_r90.sizePolicy().hasHeightForWidth())
        self.lineEdit_Yld_r90.setSizePolicy(sizePolicy)
        self.lineEdit_Yld_r90.setObjectName(_fromUtf8("lineEdit_Yld_r90"))
        self.gridLayout_2.addWidget(self.lineEdit_Yld_r90, 6, 1, 1, 1)
        self.label_Yld_rb = QtGui.QLabel(self.tab_Yld2000_2d)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Yld_rb.sizePolicy().hasHeightForWidth())
        self.label_Yld_rb.setSizePolicy(sizePolicy)
        self.label_Yld_rb.setObjectName(_fromUtf8("label_Yld_rb"))
        self.gridLayout_2.addWidget(self.label_Yld_rb, 7, 0, 1, 1)
        self.lineEdit_Yld_rb = QtGui.QLineEdit(self.tab_Yld2000_2d)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Yld_rb.sizePolicy().hasHeightForWidth())
        self.lineEdit_Yld_rb.setSizePolicy(sizePolicy)
        self.lineEdit_Yld_rb.setObjectName(_fromUtf8("lineEdit_Yld_rb"))
        self.gridLayout_2.addWidget(self.lineEdit_Yld_rb, 7, 1, 1, 1)
        self.label_Yld_a = QtGui.QLabel(self.tab_Yld2000_2d)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Yld_a.sizePolicy().hasHeightForWidth())
        self.label_Yld_a.setSizePolicy(sizePolicy)
        self.label_Yld_a.setObjectName(_fromUtf8("label_Yld_a"))
        self.gridLayout_2.addWidget(self.label_Yld_a, 8, 0, 1, 1)
        self.lineEdit_Yld_a = QtGui.QLineEdit(self.tab_Yld2000_2d)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Yld_a.sizePolicy().hasHeightForWidth())
        self.lineEdit_Yld_a.setSizePolicy(sizePolicy)
        self.lineEdit_Yld_a.setObjectName(_fromUtf8("lineEdit_Yld_a"))
        self.gridLayout_2.addWidget(self.lineEdit_Yld_a, 8, 1, 1, 1)
        self.tabWidget_Input.addTab(self.tab_Yld2000_2d, _fromUtf8(""))
        self.tab_CPB = QtGui.QWidget()
        self.tab_CPB.setObjectName(_fromUtf8("tab_CPB"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_CPB)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_CPB_a90_C = QtGui.QLabel(self.tab_CPB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_CPB_a90_C.sizePolicy().hasHeightForWidth())
        self.label_CPB_a90_C.setSizePolicy(sizePolicy)
        self.label_CPB_a90_C.setObjectName(_fromUtf8("label_CPB_a90_C"))
        self.gridLayout_6.addWidget(self.label_CPB_a90_C, 3, 0, 1, 1)
        self.lineEdit_CPB_a90_C = QtGui.QLineEdit(self.tab_CPB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_CPB_a90_C.sizePolicy().hasHeightForWidth())
        self.lineEdit_CPB_a90_C.setSizePolicy(sizePolicy)
        self.lineEdit_CPB_a90_C.setObjectName(_fromUtf8("lineEdit_CPB_a90_C"))
        self.gridLayout_6.addWidget(self.lineEdit_CPB_a90_C, 3, 1, 1, 1)
        self.label_CPB_ab_T = QtGui.QLabel(self.tab_CPB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_CPB_ab_T.sizePolicy().hasHeightForWidth())
        self.label_CPB_ab_T.setSizePolicy(sizePolicy)
        self.label_CPB_ab_T.setObjectName(_fromUtf8("label_CPB_ab_T"))
        self.gridLayout_6.addWidget(self.label_CPB_ab_T, 5, 0, 1, 1)
        self.lineEdit_CPB_ab_T = QtGui.QLineEdit(self.tab_CPB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_CPB_ab_T.sizePolicy().hasHeightForWidth())
        self.lineEdit_CPB_ab_T.setSizePolicy(sizePolicy)
        self.lineEdit_CPB_ab_T.setObjectName(_fromUtf8("lineEdit_CPB_ab_T"))
        self.gridLayout_6.addWidget(self.lineEdit_CPB_ab_T, 5, 1, 1, 1)
        self.lineEdit_CPB_a90_T = QtGui.QLineEdit(self.tab_CPB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_CPB_a90_T.sizePolicy().hasHeightForWidth())
        self.lineEdit_CPB_a90_T.setSizePolicy(sizePolicy)
        self.lineEdit_CPB_a90_T.setObjectName(_fromUtf8("lineEdit_CPB_a90_T"))
        self.gridLayout_6.addWidget(self.lineEdit_CPB_a90_T, 2, 1, 1, 1)
        self.label_CPB_ab_C = QtGui.QLabel(self.tab_CPB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_CPB_ab_C.sizePolicy().hasHeightForWidth())
        self.label_CPB_ab_C.setSizePolicy(sizePolicy)
        self.label_CPB_ab_C.setObjectName(_fromUtf8("label_CPB_ab_C"))
        self.gridLayout_6.addWidget(self.label_CPB_ab_C, 6, 0, 1, 1)
        self.lineEdit_CPB_ab_C = QtGui.QLineEdit(self.tab_CPB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_CPB_ab_C.sizePolicy().hasHeightForWidth())
        self.lineEdit_CPB_ab_C.setSizePolicy(sizePolicy)
        self.lineEdit_CPB_ab_C.setObjectName(_fromUtf8("lineEdit_CPB_ab_C"))
        self.gridLayout_6.addWidget(self.lineEdit_CPB_ab_C, 6, 1, 1, 1)
        self.lineEdit_CPB_aN_C = QtGui.QLineEdit(self.tab_CPB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_CPB_aN_C.sizePolicy().hasHeightForWidth())
        self.lineEdit_CPB_aN_C.setSizePolicy(sizePolicy)
        self.lineEdit_CPB_aN_C.setObjectName(_fromUtf8("lineEdit_CPB_aN_C"))
        self.gridLayout_6.addWidget(self.lineEdit_CPB_aN_C, 4, 1, 1, 1)
        self.lineEdit_CPB_a = QtGui.QLineEdit(self.tab_CPB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_CPB_a.sizePolicy().hasHeightForWidth())
        self.lineEdit_CPB_a.setSizePolicy(sizePolicy)
        self.lineEdit_CPB_a.setObjectName(_fromUtf8("lineEdit_CPB_a"))
        self.gridLayout_6.addWidget(self.lineEdit_CPB_a, 7, 1, 1, 1)
        self.lineEdit_CPB_a0_C = QtGui.QLineEdit(self.tab_CPB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_CPB_a0_C.sizePolicy().hasHeightForWidth())
        self.lineEdit_CPB_a0_C.setSizePolicy(sizePolicy)
        self.lineEdit_CPB_a0_C.setObjectName(_fromUtf8("lineEdit_CPB_a0_C"))
        self.gridLayout_6.addWidget(self.lineEdit_CPB_a0_C, 1, 1, 1, 1)
        self.label_CPB_a0_C = QtGui.QLabel(self.tab_CPB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_CPB_a0_C.sizePolicy().hasHeightForWidth())
        self.label_CPB_a0_C.setSizePolicy(sizePolicy)
        self.label_CPB_a0_C.setObjectName(_fromUtf8("label_CPB_a0_C"))
        self.gridLayout_6.addWidget(self.label_CPB_a0_C, 1, 0, 1, 1)
        self.label_CPB_aN = QtGui.QLabel(self.tab_CPB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_CPB_aN.sizePolicy().hasHeightForWidth())
        self.label_CPB_aN.setSizePolicy(sizePolicy)
        self.label_CPB_aN.setObjectName(_fromUtf8("label_CPB_aN"))
        self.gridLayout_6.addWidget(self.label_CPB_aN, 4, 0, 1, 1)
        self.label_CPB_a = QtGui.QLabel(self.tab_CPB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_CPB_a.sizePolicy().hasHeightForWidth())
        self.label_CPB_a.setSizePolicy(sizePolicy)
        self.label_CPB_a.setObjectName(_fromUtf8("label_CPB_a"))
        self.gridLayout_6.addWidget(self.label_CPB_a, 7, 0, 1, 1)
        self.lineEdit_CPB_a0_T = QtGui.QLineEdit(self.tab_CPB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_CPB_a0_T.sizePolicy().hasHeightForWidth())
        self.lineEdit_CPB_a0_T.setSizePolicy(sizePolicy)
        self.lineEdit_CPB_a0_T.setObjectName(_fromUtf8("lineEdit_CPB_a0_T"))
        self.gridLayout_6.addWidget(self.lineEdit_CPB_a0_T, 0, 1, 1, 1)
        self.label_CPB_a90_T = QtGui.QLabel(self.tab_CPB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_CPB_a90_T.sizePolicy().hasHeightForWidth())
        self.label_CPB_a90_T.setSizePolicy(sizePolicy)
        self.label_CPB_a90_T.setObjectName(_fromUtf8("label_CPB_a90_T"))
        self.gridLayout_6.addWidget(self.label_CPB_a90_T, 2, 0, 1, 1)
        self.label_CPB_a0_T = QtGui.QLabel(self.tab_CPB)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_CPB_a0_T.sizePolicy().hasHeightForWidth())
        self.label_CPB_a0_T.setSizePolicy(sizePolicy)
        self.label_CPB_a0_T.setObjectName(_fromUtf8("label_CPB_a0_T"))
        self.gridLayout_6.addWidget(self.label_CPB_a0_T, 0, 0, 1, 1)
        self.tabWidget_Input.addTab(self.tab_CPB, _fromUtf8(""))
        self.gridLayout_7.addWidget(self.tabWidget_Input, 1, 0, 1, 3)
        self.label_YLError = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_YLError.sizePolicy().hasHeightForWidth())
        self.label_YLError.setSizePolicy(sizePolicy)
        self.label_YLError.setObjectName(_fromUtf8("label_YLError"))
        self.gridLayout_7.addWidget(self.label_YLError, 2, 0, 1, 1)
        self.label_YLErrorShow = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_YLErrorShow.sizePolicy().hasHeightForWidth())
        self.label_YLErrorShow.setSizePolicy(sizePolicy)
        self.label_YLErrorShow.setToolTip(_fromUtf8(""))
        self.label_YLErrorShow.setObjectName(_fromUtf8("label_YLErrorShow"))
        self.gridLayout_7.addWidget(self.label_YLErrorShow, 2, 1, 1, 1)
        self.pushButton_YL = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_YL.sizePolicy().hasHeightForWidth())
        self.pushButton_YL.setSizePolicy(sizePolicy)
        self.pushButton_YL.setObjectName(_fromUtf8("pushButton_YL"))
        self.gridLayout_7.addWidget(self.pushButton_YL, 2, 2, 2, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.graphicsView_YL = PlotWidget(self.centralwidget)
        self.graphicsView_YL.setObjectName(_fromUtf8("graphicsView_YL"))
        self.gridLayout_8.addWidget(self.graphicsView_YL, 1, 1, 1, 1)
        self.treeWidget_YL = QtGui.QTreeWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_YL.sizePolicy().hasHeightForWidth())
        self.treeWidget_YL.setSizePolicy(sizePolicy)
        self.treeWidget_YL.setObjectName(_fromUtf8("treeWidget_YL"))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget_YL.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget_YL.headerItem().setFont(1, font)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_YL)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(1, font)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_YL)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_YL)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_YL)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        item_0.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_0.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item_1.setFont(0, font)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        font.setPointSize(10)
        item_1.setFont(1, font)
        self.treeWidget_YL.header().setSortIndicatorShown(False)
        self.gridLayout_8.addWidget(self.treeWidget_YL, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1133, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setCheckable(False)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName(_fromUtf8("action"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.action)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.label.setBuddy(self.comboBox_FN)
        self.label_Xval.setBuddy(self.lineEdit_Xval)
        self.label_Yval.setBuddy(self.lineEdit_Yval)
        self.label_YL.setBuddy(self.comboBox_YL)
        self.label_Vonmises_ay.setBuddy(self.lineEdit_Vonmises_ay)
        self.label_Hill_a0.setBuddy(self.lineEdit_Hill_a0)
        self.label_Hill_r0.setBuddy(self.lineEdit_Hill_r0)
        self.label_Hill_r90.setBuddy(self.lineEdit_Hill_r90)
        self.label_Yld_a0.setBuddy(self.lineEdit_Yld_a0)
        self.label_Yld_a45.setBuddy(self.lineEdit_Yld_a45)
        self.label_Yld_a90.setBuddy(self.lineEdit_Yld_a90)
        self.label_Yld_r0.setBuddy(self.lineEdit_Yld_r0)
        self.label_Yld_r45.setBuddy(self.lineEdit_Yld_r45)
        self.label_Yld_r90.setBuddy(self.lineEdit_Yld_r90)
        self.label_Yld_a.setBuddy(self.lineEdit_Yld_a)
        self.label_CPB_a90_C.setBuddy(self.lineEdit_CPB_a90_C)
        self.label_CPB_ab_T.setBuddy(self.lineEdit_CPB_ab_T)
        self.label_CPB_ab_C.setBuddy(self.lineEdit_CPB_ab_C)
        self.label_CPB_a0_C.setBuddy(self.lineEdit_CPB_a0_C)
        self.label_CPB_aN.setBuddy(self.lineEdit_CPB_aN_C)
        self.label_CPB_a.setBuddy(self.lineEdit_CPB_a)
        self.label_CPB_a90_T.setBuddy(self.lineEdit_CPB_a90_T)
        self.label_CPB_a0_T.setBuddy(self.lineEdit_CPB_a0_T)

        self.retranslateUi(MainWindow)
        self.tabWidget_Input.setCurrentIndex(3)
        QtCore.QObject.connect(self.checkBox_UE, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), MainWindow.on_checkBox_UE_clicked)
        QtCore.QObject.connect(self.pushButton_FC, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.on_pushButton_FC_clicked)
        QtCore.QObject.connect(self.comboBox_YL, QtCore.SIGNAL(_fromUtf8("activated(QString)")), MainWindow.on_comboBox_YL_activated)
        QtCore.QObject.connect(self.pushButton_YL, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.on_pushButton_YL_clicked)
        QtCore.QObject.connect(self.comboBox_FC, QtCore.SIGNAL(_fromUtf8("activated(QString)")), MainWindow.on_comboBox_FC_activated)
        QtCore.QObject.connect(self.checkBox_Bounds, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), MainWindow.on_checkBox_Bounds_clicked)
        QtCore.QObject.connect(self.comboBox_FN, QtCore.SIGNAL(_fromUtf8("activated(QString)")), MainWindow.on_comboBox_FN_activated)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.checkBox_UE, self.checkBox_Bounds)
        MainWindow.setTabOrder(self.checkBox_Bounds, self.pushButton_FC)
        MainWindow.setTabOrder(self.pushButton_FC, self.comboBox_YL)
        MainWindow.setTabOrder(self.comboBox_YL, self.lineEdit_Yld_a0)
        MainWindow.setTabOrder(self.lineEdit_Yld_a0, self.lineEdit_Yld_a45)
        MainWindow.setTabOrder(self.lineEdit_Yld_a45, self.lineEdit_Yld_a90)
        MainWindow.setTabOrder(self.lineEdit_Yld_a90, self.lineEdit_Yld_r0)
        MainWindow.setTabOrder(self.lineEdit_Yld_r0, self.lineEdit_Yld_r45)
        MainWindow.setTabOrder(self.lineEdit_Yld_r45, self.lineEdit_Yld_r90)
        MainWindow.setTabOrder(self.lineEdit_Yld_r90, self.lineEdit_Yld_a)
        MainWindow.setTabOrder(self.lineEdit_Yld_a, self.pushButton_YL)
        MainWindow.setTabOrder(self.pushButton_YL, self.comboBox_FC)
        MainWindow.setTabOrder(self.comboBox_FC, self.lineEdit_Xval)
        MainWindow.setTabOrder(self.lineEdit_Xval, self.lineEdit_Yval)
        MainWindow.setTabOrder(self.lineEdit_Yval, self.graphicsView_FC)
        MainWindow.setTabOrder(self.graphicsView_FC, self.graphicsView_YL)
        MainWindow.setTabOrder(self.graphicsView_YL, self.treeWidget_FC)
        MainWindow.setTabOrder(self.treeWidget_FC, self.treeWidget_YL)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PyForm", None))
        self.label.setText(_translate("MainWindow", "File Name:", None))
        self.groupBox_FC.setTitle(_translate("MainWindow", "FlowCurve", None))
        self.comboBox_FC.setItemText(0, _translate("MainWindow", "Swift", None))
        self.comboBox_FC.setItemText(1, _translate("MainWindow", "Voce", None))
        self.comboBox_FC.setItemText(2, _translate("MainWindow", "Gosh", None))
        self.comboBox_FC.setItemText(3, _translate("MainWindow", "Hockett_Sherby", None))
        self.comboBox_FC.setItemText(4, _translate("MainWindow", "SwiftVoce", None))
        self.comboBox_FC.setItemText(5, _translate("MainWindow", "Modified_Zener_Hollomon", None))
        self.label_Xval.setText(_translate("MainWindow", "X value:", None))
        self.label_Yval.setText(_translate("MainWindow", "Y value:", None))
        self.label_FCError.setText(_translate("MainWindow", "Error:", None))
        self.label_FCErrorShow.setText(_translate("MainWindow", "Error", None))
        self.checkBox_Bounds.setText(_translate("MainWindow", "Bounds", None))
        self.checkBox_UE.setToolTip(_translate("MainWindow", "Uniform Elongation", None))
        self.checkBox_UE.setText(_translate("MainWindow", "UE", None))
        self.pushButton_FC.setText(_translate("MainWindow", "OK", None))
        self.treeWidget_FC.headerItem().setText(0, _translate("MainWindow", "Model", None))
        self.treeWidget_FC.headerItem().setText(1, _translate("MainWindow", "Value", None))
        __sortingEnabled = self.treeWidget_FC.isSortingEnabled()
        self.treeWidget_FC.setSortingEnabled(False)
        self.treeWidget_FC.topLevelItem(0).setText(0, _translate("MainWindow", "Swift", None))
        self.treeWidget_FC.topLevelItem(0).setText(1, _translate("MainWindow", "k(phi) = A*(B + phi)^C", None))
        self.treeWidget_FC.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "A", None))
        self.treeWidget_FC.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "B", None))
        self.treeWidget_FC.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "C", None))
        self.treeWidget_FC.topLevelItem(1).setText(0, _translate("MainWindow", "Voce", None))
        self.treeWidget_FC.topLevelItem(1).setText(1, _translate("MainWindow", "k(phi) = A + B*(1 - exp(-C*phi))", None))
        self.treeWidget_FC.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "A", None))
        self.treeWidget_FC.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "B", None))
        self.treeWidget_FC.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "C", None))
        self.treeWidget_FC.topLevelItem(2).setText(0, _translate("MainWindow", "Gosh", None))
        self.treeWidget_FC.topLevelItem(2).setText(1, _translate("MainWindow", "k(phi) = A*(B + phi)^C - D", None))
        self.treeWidget_FC.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "A", None))
        self.treeWidget_FC.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "B", None))
        self.treeWidget_FC.topLevelItem(2).child(2).setText(0, _translate("MainWindow", "C", None))
        self.treeWidget_FC.topLevelItem(2).child(3).setText(0, _translate("MainWindow", "D", None))
        self.treeWidget_FC.topLevelItem(3).setText(0, _translate("MainWindow", "Hockett_Sherby", None))
        self.treeWidget_FC.topLevelItem(3).setText(1, _translate("MainWindow", "k(phi) = A + B*(1 - exp(-C*phi^D))", None))
        self.treeWidget_FC.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "A", None))
        self.treeWidget_FC.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "B", None))
        self.treeWidget_FC.topLevelItem(3).child(2).setText(0, _translate("MainWindow", "C", None))
        self.treeWidget_FC.topLevelItem(3).child(3).setText(0, _translate("MainWindow", "D", None))
        self.treeWidget_FC.topLevelItem(4).setText(0, _translate("MainWindow", "SwiftVoce", None))
        self.treeWidget_FC.topLevelItem(4).setText(1, _translate("MainWindow", "k(phi) = G*A*(B + phi)^C + (1 - G)*(D + E*(1 - exp(-F*phi)))", None))
        self.treeWidget_FC.topLevelItem(4).child(0).setText(0, _translate("MainWindow", "A", None))
        self.treeWidget_FC.topLevelItem(4).child(1).setText(0, _translate("MainWindow", "B", None))
        self.treeWidget_FC.topLevelItem(4).child(2).setText(0, _translate("MainWindow", "C", None))
        self.treeWidget_FC.topLevelItem(4).child(3).setText(0, _translate("MainWindow", "D", None))
        self.treeWidget_FC.topLevelItem(4).child(4).setText(0, _translate("MainWindow", "E", None))
        self.treeWidget_FC.topLevelItem(4).child(5).setText(0, _translate("MainWindow", "F", None))
        self.treeWidget_FC.topLevelItem(4).child(6).setText(0, _translate("MainWindow", "G", None))
        self.treeWidget_FC.topLevelItem(5).setText(0, _translate("MainWindow", "Modified_Zener_Hollomon", None))
        self.treeWidget_FC.topLevelItem(5).setText(1, _translate("MainWindow", "k(phi,phi\',T) = A*exp(B/(R*T))*phi\'**C*(1 + D*exp(-E*(phi - F)**2)*(1 - G*exp(-H*phi\'**N))", None))
        self.treeWidget_FC.topLevelItem(5).child(0).setText(0, _translate("MainWindow", "A", None))
        self.treeWidget_FC.topLevelItem(5).child(1).setText(0, _translate("MainWindow", "B", None))
        self.treeWidget_FC.topLevelItem(5).child(2).setText(0, _translate("MainWindow", "C", None))
        self.treeWidget_FC.topLevelItem(5).child(3).setText(0, _translate("MainWindow", "D", None))
        self.treeWidget_FC.topLevelItem(5).child(4).setText(0, _translate("MainWindow", "E", None))
        self.treeWidget_FC.topLevelItem(5).child(5).setText(0, _translate("MainWindow", "F", None))
        self.treeWidget_FC.topLevelItem(5).child(6).setText(0, _translate("MainWindow", "G", None))
        self.treeWidget_FC.topLevelItem(5).child(7).setText(0, _translate("MainWindow", "H", None))
        self.treeWidget_FC.topLevelItem(5).child(8).setText(0, _translate("MainWindow", "N", None))
        self.treeWidget_FC.setSortingEnabled(__sortingEnabled)
        self.label_YL.setText(_translate("MainWindow", "Yield Loci:", None))
        self.comboBox_YL.setItemText(0, _translate("MainWindow", "Vonmises", None))
        self.comboBox_YL.setItemText(1, _translate("MainWindow", "Hill48", None))
        self.comboBox_YL.setItemText(2, _translate("MainWindow", "Yld2000_2d", None))
        self.comboBox_YL.setItemText(3, _translate("MainWindow", "CPB", None))
        self.label_Vonmises_ay.setText(_translate("MainWindow", "simgay:", None))
        self.lineEdit_Vonmises_ay.setText(_translate("MainWindow", "1.0", None))
        self.tabWidget_Input.setTabText(self.tabWidget_Input.indexOf(self.tab_Vonmises), _translate("MainWindow", "Vonmises", None))
        self.label_Hill_a0.setText(_translate("MainWindow", "simga0:", None))
        self.lineEdit_Hill_a0.setText(_translate("MainWindow", "1.0", None))
        self.label_Hill_r0.setText(_translate("MainWindow", "r0:", None))
        self.lineEdit_Hill_r0.setText(_translate("MainWindow", "1.0", None))
        self.label_Hill_r90.setText(_translate("MainWindow", "r90", None))
        self.lineEdit_Hill_r90.setText(_translate("MainWindow", "1.0", None))
        self.tabWidget_Input.setTabText(self.tabWidget_Input.indexOf(self.tab_Hill48), _translate("MainWindow", "Hill48", None))
        self.label_Yld_a0.setText(_translate("MainWindow", "sigma0:", None))
        self.lineEdit_Yld_a0.setText(_translate("MainWindow", "1.0", None))
        self.label_Yld_a45.setText(_translate("MainWindow", "sigma45:", None))
        self.lineEdit_Yld_a45.setText(_translate("MainWindow", "1.0", None))
        self.label_Yld_a90.setText(_translate("MainWindow", "sigma90:", None))
        self.lineEdit_Yld_a90.setText(_translate("MainWindow", "1.0", None))
        self.label_Yld_ab.setText(_translate("MainWindow", "sigmab:", None))
        self.lineEdit_Yld_ab.setText(_translate("MainWindow", "1.0", None))
        self.label_Yld_r0.setText(_translate("MainWindow", "r0:", None))
        self.lineEdit_Yld_r0.setText(_translate("MainWindow", "1.0", None))
        self.label_Yld_r45.setText(_translate("MainWindow", "r45:", None))
        self.lineEdit_Yld_r45.setText(_translate("MainWindow", "1.0", None))
        self.label_Yld_r90.setText(_translate("MainWindow", "r90:", None))
        self.lineEdit_Yld_r90.setText(_translate("MainWindow", "1.0", None))
        self.label_Yld_rb.setText(_translate("MainWindow", "rb:", None))
        self.lineEdit_Yld_rb.setText(_translate("MainWindow", "1.0", None))
        self.label_Yld_a.setText(_translate("MainWindow", "a:", None))
        self.lineEdit_Yld_a.setText(_translate("MainWindow", "8.0", None))
        self.tabWidget_Input.setTabText(self.tabWidget_Input.indexOf(self.tab_Yld2000_2d), _translate("MainWindow", "Yld2000_2d", None))
        self.label_CPB_a90_C.setText(_translate("MainWindow", "sigma90_C:", None))
        self.lineEdit_CPB_a90_C.setText(_translate("MainWindow", "1.0", None))
        self.label_CPB_ab_T.setText(_translate("MainWindow", "sigmab_T:", None))
        self.lineEdit_CPB_ab_T.setText(_translate("MainWindow", "1.0", None))
        self.lineEdit_CPB_a90_T.setText(_translate("MainWindow", "1.0", None))
        self.label_CPB_ab_C.setText(_translate("MainWindow", "sigmab_C:", None))
        self.lineEdit_CPB_ab_C.setText(_translate("MainWindow", "1.0", None))
        self.lineEdit_CPB_aN_C.setText(_translate("MainWindow", "1.0", None))
        self.lineEdit_CPB_a.setText(_translate("MainWindow", "2.0", None))
        self.lineEdit_CPB_a0_C.setText(_translate("MainWindow", "1.0", None))
        self.label_CPB_a0_C.setText(_translate("MainWindow", "sigma0_C:", None))
        self.label_CPB_aN.setText(_translate("MainWindow", "sigmaN_C:", None))
        self.label_CPB_a.setText(_translate("MainWindow", "a:", None))
        self.lineEdit_CPB_a0_T.setText(_translate("MainWindow", "1.0", None))
        self.label_CPB_a90_T.setText(_translate("MainWindow", "sigma90_T:", None))
        self.label_CPB_a0_T.setText(_translate("MainWindow", "sigma0_T:", None))
        self.tabWidget_Input.setTabText(self.tabWidget_Input.indexOf(self.tab_CPB), _translate("MainWindow", "CPB", None))
        self.label_YLError.setText(_translate("MainWindow", "Error:", None))
        self.label_YLErrorShow.setText(_translate("MainWindow", "Error", None))
        self.pushButton_YL.setText(_translate("MainWindow", "OK", None))
        self.treeWidget_YL.headerItem().setText(0, _translate("MainWindow", "Criterion", None))
        self.treeWidget_YL.headerItem().setText(1, _translate("MainWindow", "Value", None))
        __sortingEnabled = self.treeWidget_YL.isSortingEnabled()
        self.treeWidget_YL.setSortingEnabled(False)
        self.treeWidget_YL.topLevelItem(0).setText(0, _translate("MainWindow", "Vonmises", None))
        self.treeWidget_YL.topLevelItem(0).setText(1, _translate("MainWindow", "a1^2 - a1*a2 + a2^2 = ay^2", None))
        self.treeWidget_YL.topLevelItem(1).setText(0, _translate("MainWindow", "Hill48", None))
        self.treeWidget_YL.topLevelItem(1).setText(1, _translate("MainWindow", "(G + H)*a1^2 - 2H*a1*a2 + (H + F)*a2^2 = 1", None))
        self.treeWidget_YL.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "G", None))
        self.treeWidget_YL.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "H", None))
        self.treeWidget_YL.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "F", None))
        self.treeWidget_YL.topLevelItem(2).setText(0, _translate("MainWindow", "Yld2000_2d", None))
        self.treeWidget_YL.topLevelItem(2).setText(1, _translate("MainWindow", "|s1 - s2|^a + |2s2 + s1|^a + |2s1 + s2|^a = 2*ay^a", None))
        self.treeWidget_YL.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "Alpha1", None))
        self.treeWidget_YL.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "Alpha2", None))
        self.treeWidget_YL.topLevelItem(2).child(2).setText(0, _translate("MainWindow", "Alpha3", None))
        self.treeWidget_YL.topLevelItem(2).child(3).setText(0, _translate("MainWindow", "Alpha4", None))
        self.treeWidget_YL.topLevelItem(2).child(4).setText(0, _translate("MainWindow", "Alpha5", None))
        self.treeWidget_YL.topLevelItem(2).child(5).setText(0, _translate("MainWindow", "Alpha6", None))
        self.treeWidget_YL.topLevelItem(2).child(6).setText(0, _translate("MainWindow", "Alpha7", None))
        self.treeWidget_YL.topLevelItem(2).child(7).setText(0, _translate("MainWindow", "Alpha8", None))
        self.treeWidget_YL.topLevelItem(3).setText(0, _translate("MainWindow", "CPB", None))
        self.treeWidget_YL.topLevelItem(3).setText(1, _translate("MainWindow", "|sigma_1 - k*sigma_1|^a + |sigma_2 - k*sigma_2|^a + |sigma_3 - k*sigma_3|^a = F", None))
        self.treeWidget_YL.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "C11", None))
        self.treeWidget_YL.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "C22", None))
        self.treeWidget_YL.topLevelItem(3).child(2).setText(0, _translate("MainWindow", "C33", None))
        self.treeWidget_YL.topLevelItem(3).child(3).setText(0, _translate("MainWindow", "C13", None))
        self.treeWidget_YL.topLevelItem(3).child(4).setText(0, _translate("MainWindow", "C12", None))
        self.treeWidget_YL.topLevelItem(3).child(5).setText(0, _translate("MainWindow", "C23", None))
        self.treeWidget_YL.topLevelItem(3).child(6).setText(0, _translate("MainWindow", "k", None))
        self.treeWidget_YL.setSortingEnabled(__sortingEnabled)
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.action.setText(_translate("MainWindow", "?", None))

from pyqtgraph import PlotWidget
